// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "OLD_GREEN_FROG",
            "email": "igorek.denisenko.03@mail.ru"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attachment/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/attachment/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/cards/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/cards/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/cards_label/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/cards_label/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/column/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/column/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/desk/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/desk/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/label/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/label/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/privilege/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/privilege/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/user_privilege/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/user_privilege/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/users/": {
            "get": {
                "description": "CRUD and auth users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Work with users",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all users",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n users",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get user with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD and auth users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Work with users",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all users",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n users",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get user with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/users/{id}/": {
            "get": {
                "description": "CRUD and auth users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Work with users",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all users",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n users",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get user with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD and auth users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Work with users",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all users",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n users",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get user with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD and auth users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Work with users",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all users",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n users",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get user with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.User"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/workspace/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/workspace/{id}/": {
            "get": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "description": "CRUD for models",
                "produces": [
                    "application/json"
                ],
                "summary": "Work with all existing models",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Get all models",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get n models",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Get model with id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/db.CardsLabel"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "db.Attachment": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "integer",
                    "example": 32
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "path": {
                    "type": "string",
                    "example": "/attachments/456.jpeg"
                }
            }
        },
        "db.Card": {
            "type": "object",
            "properties": {
                "assigned_id": {
                    "type": "integer",
                    "example": 660
                },
                "column_id": {
                    "type": "integer",
                    "example": 1
                },
                "creator_id": {
                    "type": "integer",
                    "example": 661
                },
                "date_created": {
                    "type": "string",
                    "example": "2019-11-09T21:21:46+00:00"
                },
                "date_expiration": {
                    "type": "string",
                    "example": "2020-11-09T21:21:46+00:00"
                },
                "description": {
                    "type": "string",
                    "example": "Some long description"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_done": {
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "type": "string",
                    "example": "Create routers"
                }
            }
        },
        "db.CardsLabel": {
            "type": "object",
            "properties": {
                "card_id": {
                    "type": "integer",
                    "example": 32
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "label_id": {
                    "type": "integer",
                    "example": 64
                }
            }
        },
        "db.Column": {
            "type": "object",
            "properties": {
                "desk_id": {
                    "type": "integer",
                    "example": 2
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "TO DO"
                }
            }
        },
        "db.Desk": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string",
                    "example": "2019-11-09T21:21:46+00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Backend"
                },
                "workspace_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "db.Label": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "SomeHexColor"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "SomeLabel"
                }
            }
        },
        "db.Privilege": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "db.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "dmitrii@mail.su"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_authorized": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Dmitrii"
                }
            }
        },
        "db.UserPrivilege": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "privilege_id": {
                    "type": "integer",
                    "example": 2
                },
                "user_id": {
                    "type": "integer",
                    "example": 3
                },
                "workspace_id": {
                    "type": "integer",
                    "example": 4
                }
            }
        },
        "db.Workspace": {
            "type": "object",
            "properties": {
                "date_created": {
                    "type": "string",
                    "example": "2019-11-09T21:21:46+00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "SomeProjectName"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PrushkaAPI",
	Description:      "Service for managing projects",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
